ScheduleManager.Api/Controllers/Common/CourseController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using ScheduleManager.Api.Models.Common;
using ScheduleManager.Domain.Common;
using ScheduleManager.Domain.Entities;

namespace ScheduleManager.Api.Controllers
{
    [Authorize]
    public class CourseController : ItemsController<Course, CourseViewModel>
    {
        public CourseController(IAsyncProvider<Course> itemProvider) : base(itemProvider)
        {
        }

        protected override IEnumerable<Course> OrderListItems(IEnumerable<Course> items)
        {
            return items.OrderBy(x => x.Title);
        }

        protected override string GetListTitle() => "Courses";
    }
}

ScheduleManager.Api/Controllers/Common/RoomController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using ScheduleManager.Api.Models.Common;
using ScheduleManager.Domain.Common;
using ScheduleManager.Domain.Entities;

namespace ScheduleManager.Api.Controllers
{
    [Authorize]
    public class RoomController : ItemsController<Room, RoomViewModel>
    {
        public RoomController(IAsyncProvider<Room> itemProvider) : base(itemProvider)
        {
        }

        protected override IEnumerable<Room> OrderListItems(IEnumerable<Room> items)
        {
            return items.OrderBy(x => x.Title);
        }

        protected override string GetListTitle() => "Rooms";
    }
}

ScheduleManager.Api/Controllers/DataManagementController.cs
using Microsoft.AspNetCore.Mvc;

namespace ScheduleManager.Api.Controllers
{
    public class DataManagementController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ScheduleManager.Api/Views/Default/Shared/Components/Navigation/_Navigation.cshtml
<ul class="mainnav sidenav sidenav-fixed collapsible" id="slide-out">
    <li class="item">
        <div class="user-view">
            <div class="background">
                <img class="responsive-img" src="/content/images/zstu_nav_background.jpg">
            </div>
            <img class="circle" src="/content/images/zstu_logo.jpg">
        </div>
    </li>
    <li class="item">
        <div class="collapsible-header"><i class="material-icons">school</i>@Texts["Faculty"]</div>
        <div class="collapsible-body">
            <ul>
                <li><a href="@Url.Action("List", "Faculty")">@Texts["Faculties"]</a></li>
                <li><a href="@Url.Action("List", "Lecturer")">@Texts["Lecturers"]</a></li>
                <li><a href="@Url.Action("List", "Department")">@Texts["Departments"]</a></li>
            </ul>
        </div>
    </li>
    <li class="item">
        <div class="collapsible-header"><i class="material-icons">weekend</i>@Texts["Components"]</div>
        <div class="collapsible-body">
            <ul>
                <li><a href="@Url.Action("List", "Attendee")">@Texts["Attendees"]</a></li>
                <li><a href="@Url.Action("List", "Room")">@Texts["Rooms"]</a></li>
                <li><a href="@Url.Action("List", "Subject")">@Texts["Subjects"]</a></li>
                <li><a href="@Url.Action("List", "Course")">@Texts["Courses"]</a></li>
                <li><a href="@Url.Action("List", "TimePeriod")">@Texts["TimePeriod"]</a></li>
            </ul>
        </div>
    </li>
    <li class="item">
        <div class="collapsible-header"><i class="material-icons">web</i>@Texts["Schedule"]</div>
        <div class="collapsible-body">
            <ul>
                <li><a href="@Url.Action("List", "Activity")">@Texts["Activities"]</a></li>
                <li><a href="@Url.Action("List", "DaySchedule")">@Texts["DaySchedule"]</a></li>
                <li><a href="@Url.Action("List", "WeekSchedule")">@Texts["WeekSchedule"]</a></li>
                <li><a href="@Url.Action("List", "ScheduleGroup")">@Texts["ScheduleGroup"]</a></li>
            </ul>
        </div>
    </li>
    <li class="item">
        <div class="collapsible-header"><i class="material-icons">settings</i>@Texts["Tools"]</div>
        <div class="collapsible-body">
            <ul>
                <li><a href="@Url.Action("Index", "DataManagement")">@Texts["DataManagement"]</a></li>
            </ul>
        </div>
    </li>
</ul>